### ISSUE TITLE
Project - 评测机 API

### ISSUE THREAD

**Issue by suntt2019** [leoleoasd/EduOJBackend#54]
# Judger API

### model
- [ ] task(resource)
  * problem, submission, run中评测相关内容

### middleware
- [x] JudgerAuthentication
  * 检测Judger请求中的password是否正确（配置文件中写的）

### API: /api/judger/...

- [x] GetScript
  - [x] 返回指定名称的Script的Presigned Url
  - [x] request & response
  - [x] controller
  - [x] test

- [x] GetRun
  * 获取一个新的Run来进行评测
  * 尝试从全局的任务管道中获取Run的ID，设定超时时间实现长轮询
  - [x] request & response
    * response中包括：language、in/out文件、task(resource)
  - [x] controller
  - [x] test
 
- [x] UpdateRun
  * 返回评测结果
  - [x] request & response
    * request中包括：status, timeUsed, memoryUsed等信息
  - [x] controller
  - [x] test

### other
- [ ] init时创建全局任务管道，将所有PENDING的Run的ID放入其中
- [ ] CreateSubmission中向全局的任务管道中放入Run的ID（优先队列...）

**Comment by leoleoasd** [comment]
run添加judger_name和message

**Comment by leoleoasd** [comment]
优先队列不实现了，通过数据库加锁查询实现。
通过redis的pub/sub实现了一个简单地polling系统，后期应该能重构为纯go的实现。
