### ISSUE TITLE
班级管理

### ISSUE THREAD

**Issue by leoleoasd** [leoleoasd/EduOJBackend#63]
创建Class（班级名称，课程名称string，描述markdown）
邀请、删除学生
通过邀请码加入班级

**Comment by suntt2019** [comment]
### models
- [ ] class
  * id
  * name
  * course_name
  * description
  * users(students and teachers)
  * invite_code

### API
- [ ] CreateClass POST /api/class
- [ ] GetClass GET /api/class/:id
- [ ] GetClasses GET /api/classes
- [ ] GetMyClasses GET /api/user/me/classes
- [ ] UpdateClass PUT /api/class/:id
- [ ] AddUser POST /api/class/:id/users
- [ ] RemoveUser DELETE /api/class/:id/users
- [ ] DeleteClass DELETE /api/class/:id
